---


- name: Destroy DIO Pipeline
  hosts: master
  gather_facts: no
  roles:
    - { role: dio/delete_pipeline }
    - { role: dio/delete_pvs,       run_all: 'true' }
  tags:
    - never
    - rebuild_dio_pipeline
    - destroy_dio_pipeline
    - dio

- name: Build DIO Pipeline
  hosts: master
  gather_facts: no
  roles:
    - { role: dio/create_pvs,       run_all: 'true' }
    - { role: dio/create_pipeline,  run_all: 'true' }
    - { role: dio/import_dashboards }
  tags:
    - never
    - rebuild_dio_pipeline
    - dio

- name: Clear caches
  hosts: all
  become: yes
  gather_facts: no
  tasks:
  - name: Clearing the cache
    shell: sync; echo 3 > /proc/sys/vm/drop_caches
    register: caches_clean
  tags:
    - always

- name: Load
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: tests/rocksdb/load, when: caches_clean, tags: ['never','load'] }

- name: Vanilla
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: tests/rocksdb/vanilla,
        when: caches_clean,
        tags: ['never','vanilla'],
        setup_res_dir: "vanilla_ycsb_wa"
      }


- name: DIO
  hosts: test
  gather_facts: yes
  become: no
  roles:
    - { role: tests/rocksdb/dio,
        when: caches_clean,
        tags: ['never','dio'],
        filter_paths: 'true',
        dio_target_events: ["open", "openat", "creat", "read", "pread64", "write", "pwrite64", "close"],
        setup_res_dir: "dio_ycsb_wa",
        dio_detailed_data: true,
        dio_detail_with_content: "off",
        dio_detail_with_arg_paths: false,
        dio_detail_with_sock_addr: false,
        dio_detail_with_sock_data: false
      }

- name: Strace
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: tests/rocksdb/strace,
        when: caches_clean,
        tags: ['never','strace'],
        setup_res_dir: "strace_ycsb_wa"
      }

- name: Sysdig
  hosts: test
  gather_facts: no
  become: no
  roles:
    - { role: tests/rocksdb/sysdig,
        when: caches_clean,
        tags: ['never','sysdig'],
        setup_res_dir: "sysdig_ycsb_wa"
      }
